### ISSUE TITLE
Any plans to include Smooth Scrollbar plugins?

### ISSUE THREAD

**Issue by andriuspetravicius** [scaccogatto/smooth-vuebar#4]
Smooth scrollbar now offers over-scroll plugin. Any plans to include functionality for that into this wrapper?

https://github.com/idiotWu/smooth-scrollbar/blob/3983d796ad110454dd89a7107ae077e3abb87353/docs/overscroll.md

**Comment by 3rownz** [comment]
+1 This is the only vue based implementation that works (without errors) for me and I also need this plugin functionality!

**Comment by gwynhokkers** [comment]
This worked for me in nuxt for SSR:  
First a register a plugin in nuxt.config:

` { src: '~/plugins/smooth-scrollbar.js', mode: 'client' },`

smooth-scrollbar.js:
```
import Vue from 'vue'
import SmoothVuebar from 'smooth-vuebar'
import OverscrollPlugin from 'smooth-scrollbar/plugins/overscroll'

Vue.use(SmoothVuebar, {
  listener: () => {},
  options: {
    damping: 0.08,
    plugins: {
      overscroll: {
        effect: 'glow',
        glowColor: '#ff5656'
      }
    }
  }
})
Vue.scrollbar.use(OverscrollPlugin)
```
